version: 3,
services:
  rust-backend-api:
    build: .
    ports:
      - "3000:3000"
    env_file: 
      - ./.env

  mongo_db:
    image: mongo
    ports:
      - '27017:27017'
    env_file: 
      - ./.env